/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static IconData personOutline =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData person =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData sort =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData messages =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData notification =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData messagesOutline =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData homeOutline =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData home =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData add =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData shoppingBagOutline =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData shoppingBag =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData feedIconOutline =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData feedIcon =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData robotArm =
      const IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData menu =
      const IconData(0xf0c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static IconData search =
      const IconData(0xf3c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

const themeColor = Color.fromRGBO(71, 77, 192, 1);
